#!/usr/bin/env bash
# Writes the licenses of everything Mullion ships to THIRD-PARTY-NOTICES.txt.
# Run through `pnpm notices` after adding or upgrading a dependency and commit
# the result; `pnpm notices --check` (also run by test/notices.test.js) fails
# when the committed file no longer matches what this script would write.
#
# What goes in, and why:
# - Electron: the app runs on it and the dmg carries the whole runtime. Its own
#   LICENSE is copied here; the notices of Chromium and the rest of the runtime
#   are already in the bundle as LICENSES.chromium.html and are only referred to.
# - JavaScript packages: every production dependency, transitive ones included
#   (`pnpm licenses list --prod`). electron-builder copies the production
#   node_modules into app.asar as they are, so unlike a bundled web app nothing
#   is tree-shaken away. devDependencies (electron-builder, and the electron
#   package that only downloads the runtime) do not go into the app.
# - Bootstrap Icons: not a package. Its SVG paths are inlined in
#   src/navigation.html, and its license text is kept in
#   third-party/bootstrap-icons/LICENSE for this script to read.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"
CHECK=false
case "${1:-}" in
  "") ;;
  --check) CHECK=true ;;
  *)
    echo "Usage: $0 [--check]" >&2
    exit 2
    ;;
esac

if [ ! -f node_modules/electron/package.json ]; then
  echo "Error: node_modules is missing. Run: pnpm install --frozen-lockfile" >&2
  exit 1
fi

# `pnpm licenses list --json` prints a plain sentence instead of JSON when there
# is nothing to list, so the output is handed to node as a file and parsed there.
LICENSES_JSON=$(mktemp)
# Written next to the output: a mv across file systems is a copy, and a copy
# interrupted halfway would leave a truncated file behind.
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP" "$LICENSES_JSON"' EXIT

pnpm licenses list --prod --json > "$LICENSES_JSON"

LICENSES_JSON="$LICENSES_JSON" node - > "$TMP" <<'NODE'
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const out = [];
const line = (text = '') => out.push(text);
const section = (title) => {
  line('#'.repeat(80));
  line(`# ${title}`);
  line('#'.repeat(80));
  line();
};
const licenseFiles = (dir) =>
  fs
    .readdirSync(dir)
    // LICENSE.spdx and the like are metadata, not the license text.
    .filter((name) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(name) && !/\.spdx$/i.test(name))
    .sort();
const readText = (file) => fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '');
const repositoryOf = (pkg) => {
  const repo = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository && pkg.repository.url;
  return repo || pkg.homepage || '';
};

line('THIRD-PARTY NOTICES');
line();
line('Mullion bundles the open source software listed below. Each entry gives the');
line('license, the packages it applies to, and the license text as shipped by the');
line('package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.');
line();

// -- Electron ---------------------------------------------------------------
const electronDir = path.join('node_modules', 'electron');
const electron = JSON.parse(fs.readFileSync(path.join(electronDir, 'package.json'), 'utf8'));
section('Electron and Chromium');
line('='.repeat(80));
line(`License: ${electron.license}`);
line();
line('Used by:');
line(`  electron ${electron.version} (${repositoryOf(electron)})`);
line();
line(readText(path.join(electronDir, 'LICENSE')));
line();
line('Electron includes Chromium, Node.js and other open source components. Their');
line('licenses are shipped with the app in LICENSES.chromium.html');
line('(Mullion.app/Contents/Resources/LICENSES.chromium.html on macOS, next to the');
line('executable on Windows and Linux) and are not repeated here.');
line();

// -- JavaScript packages ----------------------------------------------------
section('JavaScript packages (packaged into app.asar)');
const raw = fs.readFileSync(process.env.LICENSES_JSON, 'utf8').trim();
// Anything but a JSON object is pnpm's "No licenses in packages found".
const byLicense = raw.startsWith('{') ? JSON.parse(raw) : {};
const licenses = Object.keys(byLicense).sort();
if (licenses.length === 0) {
  line('Mullion has no production JavaScript dependencies. No package from');
  line('node_modules is packaged into the app.');
  line();
}
for (const license of licenses) {
  const entries = [];
  for (const pkg of byLicense[license]) {
    pkg.versions.forEach((version, index) => {
      entries.push({ name: pkg.name, version, dir: pkg.paths[index], homepage: pkg.homepage });
    });
  }
  entries.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
  // One entry per license; the texts differ only in their copyright lines, so
  // each package's own text follows the list under its name.
  line('='.repeat(80));
  line(`License: ${license}`);
  line();
  line('Used by:');
  for (const entry of entries) {
    line(`  ${entry.name} ${entry.version}${entry.homepage ? ` (${entry.homepage})` : ''}`);
  }
  line();
  for (const entry of entries) {
    const files = licenseFiles(entry.dir);
    line(`--- ${entry.name} ${entry.version} ---`);
    if (files.length === 0) {
      line('The package does not ship its license text; see its repository above.');
      line();
      continue;
    }
    for (const file of files) {
      if (files.length > 1) line(`--- ${file} ---`);
      line(readText(path.join(entry.dir, file)));
      line();
    }
  }
}

// -- Other bundled assets ---------------------------------------------------
// The version is the one src/navigation.html names in its comment, so the two
// cannot disagree without test/notices.test.js noticing.
const navigation = fs.readFileSync(path.join('src', 'navigation.html'), 'utf8');
const iconsVersion = (navigation.match(/Bootstrap Icons (\d+\.\d+\.\d+)/) || [])[1];
if (!iconsVersion) throw new Error('src/navigation.html no longer names the Bootstrap Icons version');
section('Other bundled assets');
line('='.repeat(80));
line('License: MIT');
line();
line('Used by:');
line(`  Bootstrap Icons ${iconsVersion} (https://github.com/twbs/icons), inlined as SVG in the navigation bar`);
line();
line(readText(path.join('third-party', 'bootstrap-icons', 'LICENSE')));

process.stdout.write(`${out.join('\n')}\n`);
NODE

if [ "$CHECK" = true ]; then
  if ! diff -u "$OUT" "$TMP"; then
    echo "Error: $OUT is out of date. Run: pnpm notices" >&2
    exit 1
  fi
  echo "$OUT is up to date"
  exit 0
fi

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
